alias rm='rm -i'
alias dt='/opt/darktable/bin/darktable'
alias acp='ap-cache policy'
alias acs='apt-cache search'
alias acsh='apt-cache show'
alias upgr='sudo apt-get update && sudo apt-get -V upgrade'
alias dpl='dpkg -l'
alias dpL='dpkg -L'

export EDITOR='emacsclient -c'
